name: Singularity Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      SYLABS_CLOUD_TOKEN: ${{ secrets.SYLABS_CLOUD_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
               singularity-version: 3.8.3

      - name: Build Singularity Container
        run: singularity build --fakeroot data_transfer.sif examples/data_transfer/data_transfer.def

      - name: Login to Sylabs Cloud
        run: echo "$SYLABS_CLOUD_TOKEN" | singularity remote login

      - name: Push to Sylabs Cloud Library
        run: singularity push -U data_transfer.sif library://haftommh/default/data_transfer:latest
