
name: Singularity Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      SYLABS_CLOUD_TOKEN: ${{ secrets.SYLABS_CLOUD_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Build and Push Singularity Container
        run: |
          for def_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ "${def_file}" == *".def" ]]; then
                singularity build --fakeroot "${def_file%.def}.sif" "$def_file"
                echo "$SYLABS_CLOUD_TOKEN" | singularity remote login
                singularity push -U "${def_file%.def}.sif" library://haftommh/default/"${def_file%.def}":latest
            fi
          done




